# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/middleman
image: ruby:2.3.1

cache:
  paths:
  - vendor

test:
  script:
    - apt-get update -yqqq
    - apt-get install -y jpegoptim libjpeg-progs optipng aspell aspell-en
    - bash spelling.sh
    - bundle install --path vendor
    - find source -iname '*.jpg' -print0 | xargs -0 jpegoptim -m50
    - find source -iname '*.png' -print0 | xargs -0 optipng -quiet -fix
    - bundle exec middleman build --clean --build-dir=public
  except:
    - source

pages:
  script:
    - apt-get update -yqqq
    - apt-get install -y jpegoptim libjpeg-progs optipng aspell aspell-en
    - bash spelling.sh
    - bundle install --path vendor
    - find source -iname '*.jpg' -print0 | xargs -0 jpegoptim -m50
    - find source -iname '*.png' -print0 | xargs -0 optipng -quiet -fix
    - bundle exec middleman build --clean --build-dir=public
  artifacts:
    paths:
    - public
  only:
  - source
